### ISSUE TITLE
Issue with enabling the bundle on symfony 2.8.1

### ISSUE THREAD

**Issue by ghost** [ElectricMaxxx/DoctrineOrmPhpcrAdapterBundle#13]
Is this thing completely dead?

I am getting this error with the minimum config:

```
doctrine_orm_phpcr_adapter:
    managers:
        reference-phpcr:
            defaul: doctrine_phpcr.odm.default_document_manager
        reference-dbal-orm:
            default: doctrine.orm.default_entity_manager
    adapter:
        mapping: true
        auto_generate_proxy_classes: %kernel.debug%
```

```
[InvalidArgumentException]                       
  Bundle "0" does not exist or it is not enabled.
```
