### ISSUE TITLE
non-existent service "doctrine_orm_phpcr_adapter.adapter.default_adapter_manager"

### ISSUE THREAD

**Issue by bigfoot90** [ElectricMaxxx/DoctrineOrmPhpcrAdapterBundle#9]
I'm trying to use your bundle on Symfony 2.6, but I'm getting `ServiceNotFoundException`

```
You have requested a non-existent service "doctrine_orm_phpcr_adapter.adapter.default_adapter_manager".
```

Do I need to configure something?

**Comment by bigfoot90** [comment]
I've added this to my `config.yml`

```
doctrine_orm_phpcr_adapter:
    adapter:
        auto_mapping: true
        auto_generate_proxy_classes: true
```

but the listeners seems not working yet

**Comment by ElectricMaxxx** [comment]
There should be a base config in the readme, isn't it? Otherwise, i will have a look tonight. Not sure if i have symfony 2.6 in the travis matrix. You can add your complete config for the Adapter? So i will test that. =

**Comment by ElectricMaxxx** [comment]
@bigfoot90 i added some more configuration hints into the readme, will do a better documentation later. But you will find documentation for the mapping on the library https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter
I also added test for the existence of the existence of the EventListeners and Configuration. This should work now.

**Comment by bigfoot90** [comment]
First thank you very much for the quickly respoce.

I've seen the new section in the `README.md`, but it seems wrong, maybe you have not updated the configuration.php?

My currenty configuration is

``` yml
doctrine:
    dbal:
        ...

    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                mappings:
                    BestCommonBundle: ~
                    ...

doctrine_phpcr:
    odm:
        auto_mapping: false
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
            BestCmsBundle: ~

    session:
        backend:
            type: doctrinedbal
            profiling: %kernel.debug%
            logging: true
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes
        workspace: default

doctrine_orm_phpcr_adapter:
    managers:
        reference-phpcr:
            defaul: doctrine_phpcr.odm.default_document_manager
        reference-dbal-orm:
            default: doctrine.orm.default_entity_manager
    adapter:
        auto_generate_proxy_classes: true
        default_adapter_manager: default
        adapter_managers:
            default:
                mappings:
                    BestSpeedDateBundle:
                        type: 'annotation'
                        prefix: '\Entity'
                        dir: '%kernel.root_dir%/../src/Best/CommonBundle/Entity/'
                        is_bundle: false
                        mapping: true
                auto_mapping: true
```

Another thing I don't understand is if I need `doctrine orm` annotations. In your [Entity annotations example](https://github.com/ElectricMaxxx/DoctrineOrmOdmAdapter) you didn't add orm annotations.

And here is my current entity:

``` php
/**
 * Redirect
 *
 * @ORM\Table()
 * @ORM\Entity()
 *
 * @ODMAdapter\ObjectAdapter()
 */
class Entity
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    public $uuid;

    /**
     * @var Page
     *
     * @ORM\Column(type="string", nullable=true)
     *
     * @ODMAdapter\ReferencePhpcr(
     *  referencedBy="uuid",
     *  inversedBy="uuid",
     *  targetObject="Best\CmsBundle\Document\Page"
     * )
     */
    public $target;
}
```

and `Page` docuement:

``` php
/**
 * @PHPCR\Document(
 *      referenceable=true,
 *      mixins={"mix:lastModified"}
 * )
 */
class Page extends StaticContent
{
    /**
     * @var string
     *
     * @PHPCR\Uuid
     */
    public $uuid;
}
```

What I'm wrong?
